name: afisha
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  talker_flutter: ^3.2.0
  get_it: ^7.6.0
  provider: ^6.0.5
  go_router: ^10.0.0
  top_snackbar_flutter: ^3.1.0
  cached_network_image: ^3.2.3
  html_unescape: ^2.0.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  readmore: ^2.2.0
  flutter_spinkit: ^5.2.0
  share_plus: ^7.0.2
  easy_localization: ^3.0.2
  assorted_layout_widgets: ^8.0.4
  intl: ^0.18.0
  calendar_date_picker2: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/translations/

